### PR TITLE
Support file copying on forbidden

### PR DESCRIPTION
**Pull request by CodeingBoy**
Clean version of #21.

### CODE REVIEW

**Comment by FloridaStream** [comment]
Can you add an option to automatically delete the copied files after 1 day of existence? or something that prevents the user from having to delete manually. That would be very useful.

Thanks for the update @CodeingBoy ☕️

**Comment by CodeingBoy** [comment]
> Can you add an option to automatically delete the copied files after 1 day of existence? or something that prevents the user from having to delete manually. That would be very useful.
> 
> Thanks for the update @CodeingBoy

No, because the worker is stateless. Due to worker limitation, I can't record create time in worker, or run auto deletion periodically.

Quick ideas:
1. record create time in KV and provide a button allowing user manually delete those obsoleted files
2. (If we can) listen for ending of request and delete it

I will add this to my to-do list but this will not be the next feature I will implement.

**Comment by maple3142** [comment]
@CodeingBoy For 1, I don't think it should be used, as I want to avoid KV. (Because it needs subscription.)
For 2, I don't think it is possible, because worker has limited execution time and memory, so you can't download the whole file body and send it to client.

But I wonder what happens if you delete the file right after you start the download.

**Comment by CodeingBoy** [comment]
> @CodeingBoy For 1, I don't think it should be used, as I want to avoid KV. (Because it needs subscription.)
> For 2, I don't think it is possible, because worker has limited execution time and memory, so you can't download the whole file body and send it to client.

That's why we need more thinking.

> But I wonder what happens if you delete the file right after you start the download.

That's a good idea, though I don't know what will happen. Also this will cause more copy request, Google won't happy with that.

**Pull request closed without merging**
