### PR TITLE
Add Aria2 download support

### PR DESCRIPTION
**Pull request by CodeingBoy**

### CODE REVIEW

**Comment by CodeingBoy** [comment]
Notice: does not support download more than 1000 files

**Comment by maple3142** [comment]
Looks good!
But I don't have time to review this today, maybe tomorrow, sorry!

**Comment by CodeingBoy** [comment]
No problem!

> Looks good!
> But I don't have time to review this today, maybe tomorrow, sorry!

No problem.

**Comment by maple3142** [comment]
In fact, I doubt whether this has to be implemented in website?
It would be much better to use [browser extension](https://github.com/maple3142/aria2-manager) do handle this, and it can bypass some limitation too. Such as CORS issues.

It would be better to have a option to let user to easily copy links by selecting files, which is more beneficial than only support 1 download manager(aria2).

**Comment by CodeingBoy** [comment]
> In fact, I doubt whether this has to be implemented in website?
> It would be much better to use [browser extension](https://github.com/maple3142/aria2-manager) do handle this, and it can bypass some limitation too. Such as CORS issues.
> 
> It would be better to have a option to let user to easily copy links by selecting files, which is more beneficial than only support 1 download manager(aria2).

Of course we can separate them, but offering this feature in web interface will be convenient. User can download with aria2 without copy/pasting them or connect this api to their manager. Also, it based on the worker drive API, it's tightly coupled. I think the web interface is the best place it gets implemented.

For some power users copy & pasting urls will fit their needs, but for normal users, handling thousands of files while keeping folder structures intact is difficult. Even they have every files' url, they still needs setting other things, like download directory. It will be very easy by parsing and organizing file info, fill in generated download directory and ships them to aria2. What you need is a few clicks and wait.

For my use case, I have 200+ folders and much more files to download, within several clicks it just gets done.

For exporting urls, you need to think about what should you provide to users. Perhaps they need file name, size, author... What about a selection box? But that will bring much work, so I'm not going to implement this, maybe later.

**Comment by maple3142** [comment]
@CodeingBoy The problem is this is tighyly coupled with Aria2 only, and this doesn't work for other downloaders such as IDM, JDownloader and so on.

**Comment by CodeingBoy** [comment]
> @CodeingBoy The problem is this is tighyly coupled with Aria2 only, and this doesn't work for other downloaders such as IDM, JDownloader and so on. And it is unreasonable to expect a website to support all kinds of downloader, so I think this should be handled at user's browser level.

Fine, I will support exporting download urls at weekend.

**Comment by CodeingBoy** [comment]
> > @CodeingBoy The problem is this is tighyly coupled with Aria2 only, and this doesn't work for other downloaders such as IDM, JDownloader and so on. And it is unreasonable to expect a website to support all kinds of downloader, so I think this should be handled at user's browser level.
> 
> Fine, I will support exporting download urls at weekend.

Because of Black Friday and Cyber Monday, this feature will be delayed. Stay tuned.

**Comment by CodeingBoy** [comment]
@maple3142 I will implement url exporting in another PR. If you think this PR alone is good you can merge it now.

**Comment by maple3142** [comment]
I still believe that this should be handled by browser instead, not integrated into this project.
Because there is not reason to only favor Aria2 instead of others.

**Comment by CodeingBoy** [comment]
> I still believe that this should be handled by browser instead, not integrated into this project.
> Because there is not reason to only favor Aria2 instead of others.

Fine, closing it.

**Pull request closed without merging**
